# Lecture 2: NumPy
- free and open source library for mathematical operations in science and engineering 
- building block of STEM 
- efficient multidimensional ____ 
- Uses arrays instead of python lists, which is much faster and more efficient than python lists (note: it's difficult to apply mathematical operations on lists) 

## Important attributes
- ndarray: any length of array? 

In [2]:
import numpy as np #np is now an alias or shorthand 

In [3]:
#let's build our first array 
myList = [4,5,7,2,3,0,2]    #list
myArray = np.array(myList)  #converting list into an array

print(type(myList))
print(myList)
print(type(myArray))
print(myArray)

<class 'list'>
[4, 5, 7, 2, 3, 0, 2]
<class 'numpy.ndarray'>
[4 5 7 2 3 0 2]


In [4]:
myArray = np.array([4,5,654,34,2]) #can also define it within the np.array function
myArray

array([  4,   5, 654,  34,   2])

## arange() function 
-does the same thing as range but builts an numpy array 

In [11]:
print(type(list(range(0,20))))
print(type(np.arange(0,20)))
print(np.arange(2,41,2))  #can skip by 2; note it is inclusive of LL (lower limit) but excludes UL (upper limit)
print(np.arange(0,5,0.4)) #arange works with decimals too 
print(np.arange(5,0,-0.5)) #use negative sign to count backwards


<class 'list'>
<class 'numpy.ndarray'>
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[0.  0.4 0.8 1.2 1.6 2.  2.4 2.8 3.2 3.6 4.  4.4 4.8]
[5.  4.5 4.  3.5 3.  2.5 2.  1.5 1.  0.5]


## Speed test between numpy array and python list 
- see bassel's code 

In [12]:
#0-d array 
a0 = np.array(30)
a0.ndim

0

In [13]:
#1-d
a1 = np.array([4,6,7,8])
a1.ndim

1

In [57]:
#2-d array aka matrices (needs to be same length)
a2 = np.array([[2,3,4],[5,6,7]])
print(a2)
print(a2.ndim)
print(a2.shape) #gives columns and row count
print(f"This matrix has {a2.shape[0]} rows and {a2.shape[1]} columns.")

a21 = np.array([[2,3,4]]) #this is also a 2d array because of the double brackets. it sees 2nd dimension as null 
print(a21)
print(a21.ndim) 

[[2 3 4]
 [5 6 7]]
2
(2, 3)
This matrix has 2 rows and 3 columns.
[[2 3 4]]
2


In [37]:
#3-d array 
d3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]
               ,[[10,11,12],[13,14,15],[16,17,18]]
               ,[[19,20,21],[22,23,24],[25,26,27]]
               ])
print(d3)
print(d3.shape)
print(d3.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)
3


## Arithmetic operations

In [24]:
#when matrices are the same shape 
arr1 = np.array([4,6,7])
arr2 = np.array([10,20,30])

print(arr1 + arr2) #it does the operation and prints value by value
print(arr1 * arr2)
print(arr1 / arr2)


[14 26 37]
[ 40 120 210]
[0.4        0.3        0.23333333]


In [26]:
#when matrices are different shapes aka broadcasting 
    #multiplying 1d by 0d is acceptable 
a = np.array(5)

print(a*arr1) #it broadcasted "a" multiple times to fit the shape of the other element 

[20 30 35]
[20 30 35]


In [34]:
#reshaping a matrix 

arrr3 = np.array([1,2,3,4,5,6,7,8,9])
print(arrr3)
print(arrr3.shape)

arr4 = arrr3.reshape(3,3)
print(arr4)
print(arr4.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [45]:
#flatten arrays to reduce dimensionaltiy 
print(arr4)
print(arr4.flatten())

#flatten works like reshape -1 as well to reduce dimensionality 
print(arr4.reshape(1,1,-1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[[1 2 3 4 5 6 7 8 9]]]


In [50]:
arr1 = np.array([10,20,30])
arr2 = np.array([5,2,7])

print(np.mod(arr1,arr2)) #mod is % i.e. the remainder after division 
print(np.matmul(arr1,arr2))
print(np.add(arr1,arr2))


[0 0 2]
300
[15 22 37]


In [68]:
#concatenate 
arr1 = np.array([[10,20,5],
                [4,5,6],
                [10,20,30]])
arr2 = np.array([[7,9,6],[10,11,4],[20,30,3]])

#concatenate stacks 
print(np.concatenate((arr1,arr2))) #default axis is to concat vertically 
print(np.concatenate((arr1,arr2),axis=1)) #axis = 1 tells numpy to concat horizontally


[[10 20  5]
 [ 4  5  6]
 [10 20 30]
 [ 7  9  6]
 [10 11  4]
 [20 30  3]]
[[10 20  5  7  9  6]
 [ 4  5  6 10 11  4]
 [10 20 30 20 30  3]]


## Text arrays

In [55]:
a = np.array(['a','b','test',5]) #can have a mix of data types
print(a)
print(type(a))

['a' 'b' 'test' '5']
<class 'numpy.ndarray'>


In [69]:
greetings = np.array(['hello','welcome'])
subj = np.array(['learners','to the class'])

#add or blend the two text arrays together 
np.concatenate((greetings,subj))


array(['hello', 'welcome', 'learners', 'to the class'], dtype='<U12')

In [70]:
#replace function 
    ## replace(array name, 'string to look for','string to replace with')
arr3 = np.array(["hello mykel - how are you?","hello chai - how are things going?"])

np.char.replace(arr3,'hello',"Hi")

array(['Hi mykel - how are you?', 'Hi chai - how are things going?'],
      dtype='<U31')

In [71]:
#convert to upper case 
arr3_up = np.char.upper(arr3)
print(arr3_up)

['HELLO MYKEL - HOW ARE YOU?' 'HELLO CHAI - HOW ARE THINGS GOING?']


## run stats f(x)s in numpy

In [72]:
arrr3 = np.array([1,2,3,4,5,6,7,8,9])
np.mean(arrr3)


5.0

In [79]:
arr1 = np.array([[1,2,6],
                [1,2,6],
                [1,2,6]])

print(np.mean(arr1)) #full mean of all elements in matrix
print(np.mean(arr1,axis=1)) #row mean
print(np.mean(arr1,axis=0)) #col mean

3.0
[3. 3. 3.]
[1. 2. 6.]


In [80]:
#median 
print(np.median(arr1))
print(np.median(arr1,axis=1))
print(np.median(arr1,axis=0))

2.0
[2. 2. 2.]
[1. 2. 6.]


## filtering and slicing

In [90]:
#Grab all the numbers greater than 4
print(arr1)
#define a mask (filter condition)
mask = np.where(arr1>=2)
print(mask) #it builts a weird tuple
#apply the mask 
filtered_arr = arr1[mask]
print(filtered_arr)

#quicker version 
arr1[arr1>=1]

[[1 2 6]
 [1 2 6]
 [1 2 6]]
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([1, 2, 1, 2, 1, 2], dtype=int64))
[2 6 2 6 2 6]


array([1, 2, 6, 1, 2, 6, 1, 2, 6])

In [92]:
#Build an array that shows whether the number is even or odd 

np.where(arr1%2==0,"Even","Odd")

array([['Odd', 'Even', 'Even'],
       ['Odd', 'Even', 'Even'],
       ['Odd', 'Even', 'Even']], dtype='<U4')

In [94]:
#give a list of even and odd 
print(arr1[arr1 %2==0]) #even 
print(arr1[arr1 %2!=0]) #odd 


[2 6 2 6 2 6]
[1 1 1]


## Indexing and slicing

In [97]:
#slicing 1D arrays 
a = np.array([22,3,1,43,54])
      #index: 0  1 2 3  4

print(a[1]) #gives the 2nd element 
print(a[-1]) # gives las element
print(a[:3]) #gives first 3 elements starting from the beginning

3
54
[22  3  1]


In [101]:
#slicing 2D arrays 
arr1 = np.array([[1,2,6],
                [1,2,6],
                [1,2,6]])

print(arr1[2,1]) #grabbing using r1c1 method
print(arr1[2][1]) #grabbing by first indexing the row, and then identifying which element within the row 

print(arr1[:,:2]) #grab all the rows, and only columns 1 & 2 for each row 

2
2
[[1 2]
 [1 2]
 [1 2]]


In [127]:
#indexing 3d matrix 
d3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]
               ,[[10,11,12],[13,14,15],[16,17,18]]
               ,[[19,20,21],[22,23,24],[25,26,27]]
               ])

print(d3)

d3[0,2,2] #9 first matrix of 3, 3rd row, 3rd element 



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


9

## Group project instructions (Sanaa, Ramin, Oday)
- Create a NumPy array containing the integers from 4 to 100 with 2 steps.
- Calculate the square values of each element in the array above
- Find the average of all values
- Convert the array to 2d
- Build a new array with the first 20 elements of the original array

In [103]:
#Create a NumPy array containing the integers from 4 to 100 with 2 steps.
arr1 = np.array(range(4,101,2))
print(arr1)

[  4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36  38
  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74
  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [123]:
#Calculate the square values of each element in the array above
arr2 = arr1**2
print(arr2)

print(np.square(arr1))

[   16    36    64   100   144   196   256   324   400   484   576   676
   784   900  1024  1156  1296  1444  1600  1764  1936  2116  2304  2500
  2704  2916  3136  3364  3600  3844  4096  4356  4624  4900  5184  5476
  5776  6084  6400  6724  7056  7396  7744  8100  8464  8836  9216  9604
 10000]
[   16    36    64   100   144   196   256   324   400   484   576   676
   784   900  1024  1156  1296  1444  1600  1764  1936  2116  2304  2500
  2704  2916  3136  3364  3600  3844  4096  4356  4624  4900  5184  5476
  5776  6084  6400  6724  7056  7396  7744  8100  8464  8836  9216  9604
 10000]


In [111]:
#Find the average of all values
allave = np.average(arr1)
print(allave)

52.0


In [122]:
#Convert the array to 2d 
arr1_2d= arr1.reshape(7,7)
print(arr1_2d)

arr1_2d.ndim

[[  4   6   8  10  12  14  16]
 [ 18  20  22  24  26  28  30]
 [ 32  34  36  38  40  42  44]
 [ 46  48  50  52  54  56  58]
 [ 60  62  64  66  68  70  72]
 [ 74  76  78  80  82  84  86]
 [ 88  90  92  94  96  98 100]]


2

In [121]:
#Build a new array with the first 20 elements of the original array
arr1_20 = arr1[:20]
print(arr1_20)
len(arr1_20)

[ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42]


20