# Lecture 2: NumPy
- free and open source library for mathematical operations in science and engineering 
- building block of STEM 
- efficient multidimensional ____ 
- Uses arrays instead of python lists, which is much faster and more efficient than python lists (note: it's difficult to apply mathematical operations on lists) 

## Important attributes
- ndarray: any length of array? 

In [2]:
import numpy as np #np is now an alias or shorthand 

In [3]:
#let's build our first array 
myList = [4,5,7,2,3,0,2]    #list
myArray = np.array(myList)  #converting list into an array

print(type(myList))
print(myList)
print(type(myArray))
print(myArray)

<class 'list'>
[4, 5, 7, 2, 3, 0, 2]
<class 'numpy.ndarray'>
[4 5 7 2 3 0 2]


In [4]:
myArray = np.array([4,5,654,34,2]) #can also define it within the np.array function
myArray

array([  4,   5, 654,  34,   2])

## arange() function 
-does the same thing as range but builts an numpy array 

In [11]:
print(type(list(range(0,20))))
print(type(np.arange(0,20)))
print(np.arange(2,41,2))  #can skip by 2; note it is inclusive of LL (lower limit) but excludes UL (upper limit)
print(np.arange(0,5,0.4)) #arange works with decimals too 
print(np.arange(5,0,-0.5)) #use negative sign to count backwards


<class 'list'>
<class 'numpy.ndarray'>
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[0.  0.4 0.8 1.2 1.6 2.  2.4 2.8 3.2 3.6 4.  4.4 4.8]
[5.  4.5 4.  3.5 3.  2.5 2.  1.5 1.  0.5]


## Speed test between numpy array and python list 
- see bassel's code 

In [12]:
#0-d array 
a0 = np.array(30)
a0.ndim

0

In [13]:
#1-d
a1 = np.array([4,6,7,8])
a1.ndim

1

In [57]:
#2-d array aka matrices (needs to be same length)
a2 = np.array([[2,3,4],[5,6,7]])
print(a2)
print(a2.ndim)
print(a2.shape) #gives columns and row count
print(f"This matrix has {a2.shape[0]} rows and {a2.shape[1]} columns.")

a21 = np.array([[2,3,4]]) #this is also a 2d array because of the double brackets. it sees 2nd dimension as null 
print(a21)
print(a21.ndim) 

[[2 3 4]
 [5 6 7]]
2
(2, 3)
This matrix has 2 rows and 3 columns.
[[2 3 4]]
2


In [37]:
#3-d array 
d3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]
               ,[[10,11,12],[13,14,15],[16,17,18]]
               ,[[19,20,21],[22,23,24],[25,26,27]]
               ])
print(d3)
print(d3.shape)
print(d3.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)
3


## Arithmetic operations

In [24]:
#when matrices are the same shape 
arr1 = np.array([4,6,7])
arr2 = np.array([10,20,30])

print(arr1 + arr2) #it does the operation and prints value by value
print(arr1 * arr2)
print(arr1 / arr2)


[14 26 37]
[ 40 120 210]
[0.4        0.3        0.23333333]


In [26]:
#when matrices are different shapes aka broadcasting 
    #multiplying 1d by 0d is acceptable 
a = np.array(5)

print(a*arr1) #it broadcasted "a" multiple times to fit the shape of the other element 

[20 30 35]
[20 30 35]


In [34]:
#reshaping a matrix 

arrr3 = np.array([1,2,3,4,5,6,7,8,9])
print(arrr3)
print(arrr3.shape)

arr4 = arrr3.reshape(3,3)
print(arr4)
print(arr4.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [45]:
#flatten arrays to reduce dimensionaltiy 
print(arr4)
print(arr4.flatten())

#flatten works like reshape -1 as well to reduce dimensionality 
print(arr4.reshape(1,1,-1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[[1 2 3 4 5 6 7 8 9]]]


In [50]:
arr1 = np.array([10,20,30])
arr2 = np.array([5,2,7])

print(np.mod(arr1,arr2)) #mod is % i.e. the remainder after division 
print(np.matmul(arr1,arr2))
print(np.add(arr1,arr2))


[0 0 2]
300
[15 22 37]


In [ ]:
#concatenate 
arr1 = np.array([10,20],[4,5])
arr2 = np.array([7,9],[10,11])

#concatenate stacks 

## Text arrays

In [55]:
a = np.array(['a','b','test',5]) #can have a mix of data types
print(a)
print(type(a))

['a' 'b' 'test' '5']
<class 'numpy.ndarray'>


In [ ]:
greetings = np.array(['hello','welcome'])
subj = np.array(['learners','to the class'])

#add or blend the two text arrays together 
